.devops/code-review-pipelines.yml, .devops/deploy-pipelines.yml, .github/workflows/pr-title.yml, .pre-commit-config.yaml
=> feat: Add code review & deploy pipeline

src/test/resources/stub/mappings/bizEventsService/bizEvents_Get_TransactionsList_ERROR.json, src/test/resources/stub/mappings/bizEventsService/bizEvents_Get_TransactionsList_NOT_FOUND.json, src/test/resources/stub/mappings/bizEventsService/bizEvents_Get_TransactionsList_OK.json
=> chore: PAPU-206 fix stubbing test files

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, helm/values.yaml
=> chore: P4PU-185: Migrate p4pa to arc

.devops/deploy-pipelines.yml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
- added jobs to run collection postman
=> chore: PAPU-148 added jobs to run collection postman

postman/pagopa-arc-E2E.postman_collection.json, postman/template-env.secure-file.json.txt
- added collection postman with http call to inject events
=> chore: PAPU-45 inject event into biz-events via http call

openapi/pagopa-arc-be.openapi.yaml
- added transaction details endpoint on swagger openapi
=> chore: P4PU-198 added transaction details endpoint on swagger openapi

src/main/java/it/gov/pagopa/arc/connector/bizevents/BizEventsConnector.java, src/main/java/it/gov/pagopa/arc/connector/bizevents/BizEventsConnectorImpl.java, src/main/java/it/gov/pagopa/arc/connector/bizevents/BizEventsRestClient.java, src/main/java/it/gov/pagopa/arc/connector/bizevents/dto/BizEventsCartItemDTO.java, src/main/java/it/gov/pagopa/arc/connector/bizevents/dto/BizEventsInfoTransactionDTO.java, src/main/java/it/gov/pagopa/arc/connector/bizevents/dto/BizEventsTransactionDetailsDTO.java, src/main/java/it/gov/pagopa/arc/connector/bizevents/dto/BizEventsUserDetailDTO.java, src/main/java/it/gov/pagopa/arc/connector/bizevents/dto/BizEventsWalletInfoDTO.java, src/main/java/it/gov/pagopa/arc/connector/bizevents/enums/Origin.java, src/main/java/it/gov/pagopa/arc/connector/bizevents/enums/PaymentMethod.java, src/test/java/it/gov/pagopa/arc/connector/bizevents/BizEventsConnectorImplTest.java, src/test/java/it/gov/pagopa/arc/exception/ArcExceptionHandlerTest.java, src/test/java/it/gov/pagopa/arc/utils/MemoryAppender.java, src/test/java/it/gov/pagopa/arc/utils/TestUtils.java, src/test/resources/stub/mappings/bizEventsService/bizEvents_Get_TransactionDetails_ERROR.json, src/test/resources/stub/mappings/bizEventsService/bizEvents_Get_TransactionDetails_NOT_FOUND.json, src/test/resources/stub/mappings/bizEventsService/bizEvents_Get_TransactionDetails_OK.json
- Added transaction details endpoint into feign client of bizEvents
- added junit
=> chore: P4PU 199 added endpoint in the feign client to retrieve transaction details from biz events

openapi/pagopa-arc-be.openapi.yaml, src/main/java/it/gov/pagopa/arc/connector/bizevents/BizEventsConnectorImpl.java, src/main/java/it/gov/pagopa/arc/exception/ArcExceptionHandler.java, src/main/java/it/gov/pagopa/arc/exception/custom/BizEventsNotFoundException.java, src/test/java/it/gov/pagopa/arc/connector/bizevents/BizEventsConnectorImplTest.java
=> fix: P4PU-258 add custom not found exception

src/main/java/it/gov/pagopa/arc/connector/bizevents/BizEventsConnectorImpl.java, src/main/java/it/gov/pagopa/arc/service/bizevents/BizEventsServiceImpl.java
=> fix: P4PU-260 update constructor

openapi/pagopa-arc-be.openapi.yaml
- added receipt endpoint in openapi swagger
=> chore: P4PU-241 added receipt endpoint

src/main/java/it/gov/pagopa/arc/controller/TransactionsControllerImpl.java, src/main/java/it/gov/pagopa/arc/service/TransactionsService.java, src/main/java/it/gov/pagopa/arc/service/TransactionsServiceImpl.java, src/main/java/it/gov/pagopa/arc/service/bizevents/BizEventsService.java, src/main/java/it/gov/pagopa/arc/service/bizevents/BizEventsServiceImpl.java, src/test/java/it/gov/pagopa/arc/controller/TransactionsControllerTest.java, src/test/java/it/gov/pagopa/arc/service/TransactionsServiceTest.java, src/test/java/it/gov/pagopa/arc/service/bizevents/BizEventsServiceImplTest.java
- implemented business logic to retrieve transaction receipt
- added junit tests
=> feat: P4PU-242 implement business logic to retrieve transaction receipt

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
=> fix: acr reference in helm chart

helm/values.yaml, src/main/java/it/gov/pagopa/arc/service/bizevents/BizEventsServiceImpl.java, src/main/resources/application.yml
- Added resource rest-client pull-payment
- Added Values
=> chore: P4PU-284 added rest-client pull-payment resources and added values

build.gradle.kts, openapi/pagopa-arc-be.openapi.yaml
-Added payment notices endpoint
=> chore: P4PU-286 updated swagger openapi with payment notices endpoint

src/main/java/it/gov/pagopa/arc/controller/PaymentNoticesControllerImpl.java, src/main/java/it/gov/pagopa/arc/service/PaymentNoticesService.java, src/main/java/it/gov/pagopa/arc/service/PaymentNoticesServiceImpl.java, src/main/java/it/gov/pagopa/arc/service/pullpayment/PullPaymentService.java, src/main/java/it/gov/pagopa/arc/service/pullpayment/PullPaymentServiceImpl.java, src/test/java/it/gov/pagopa/arc/controller/PaymentNoticesControllerImplTest.java, src/test/java/it/gov/pagopa/arc/service/PaymentNoticesServiceImplTest.java, src/test/java/it/gov/pagopa/arc/service/pullpayment/PullPaymentServiceImplTest.java
- Added business logic to retrieve filtered payment notices
- Added test
=> feat: P4PU-287 added payment notices business logic

helm/values.yaml
added secret to helm chart for jwt signing
required for signing jwt tokens
=> chore: P4PU-332 added secret to helm chart

src/main/resources/application.yml
increased log level for spring security
=> chore: P4PU increased log level

src/main/resources/application.yml
=> chore: P4PU increased log level spring web

postman/pagopa-arc-E2E.postman_collection.json, postman/template-env.secure-file.json.txt
- updated collection postman with payment notices test
- updated env template
=> chore: P4PU-288 updated collection postman with payment notices test 

src/main/java/it/gov/pagopa/arc/connector/pullpayment/PullPaymentRestClient.java
- fixed date client pull payment
=> fix: P4PU-392 fix date client pull payment

helm/values.yaml, src/main/resources/application.yml
- added secret 
- updated externalConfigMapValues
=> chore: P4PU-362 added secret and updated externalConfigMapValues

openapi/pagopa-arc-be.openapi.yaml
Fixed naming in open api definition to be camel case
Issue was causing missalignment with front end specification
The token generation in local environment is actully returning value in camel case, so this behavior was extended also to open api
=> fix: P4PU fixed naming in camel case

.github/workflows/pr-title.yml
updated yaml for pr validations
=> chore: P4PU-000 fixed github action title validation

openapi/pagopa-arc-be.openapi.yaml, src/main/java/it/gov/pagopa/arc/config/OAuth2LoginConfig.java, src/main/java/it/gov/pagopa/arc/controller/AssistanceControllerImpl.java, src/main/java/it/gov/pagopa/arc/service/ZendeskAssistanceTokenService.java, src/test/java/it/gov/pagopa/arc/config/OAuth2LoginConfigTest.java
- added assistance endpoint
- updated class OAuth2LoginConfig
=> chore: [P4PU-361] added assistance endpoint

openapi/pagopa-arc-be.openapi.yaml, src/main/java/it/gov/pagopa/arc/dto/mapper/IamUserInfoDTO2UserInfo.java, src/test/java/it/gov/pagopa/arc/dto/mapper/IamUserInfoDTO2UserInfoImplTest.java, src/test/java/it/gov/pagopa/arc/fakers/auth/IamUserInfoDTOFaker.java
In open api definition added auth/user endpoint
added dto for handling user object
To provide user info functionality open api and new dtos were added
=> feat: [P4PU-385] user info - splitted branch openapi part

src/main/java/it/gov/pagopa/arc/controller/AuthControllerImpl.java, src/main/java/it/gov/pagopa/arc/exception/ArcExceptionHandler.java, src/main/java/it/gov/pagopa/arc/exception/custom/InvalidTokenException.java, src/main/java/it/gov/pagopa/arc/service/AuthService.java, src/main/java/it/gov/pagopa/arc/service/AuthServiceImpl.java, src/main/java/it/gov/pagopa/arc/service/TokenStoreServiceImpl.java, src/main/java/it/gov/pagopa/arc/service/ZendeskAssistanceTokenServiceImpl.java, src/main/java/it/gov/pagopa/arc/utils/SecurityUtils.java, src/test/java/it/gov/pagopa/arc/config/OAuth2LoginConfigTest.java, src/test/java/it/gov/pagopa/arc/controller/AuthControllerImplTest.java, src/test/java/it/gov/pagopa/arc/exception/ArcExceptionHandlerTest.java, src/test/java/it/gov/pagopa/arc/fakers/auth/UserInfoDTOFaker.java, src/test/java/it/gov/pagopa/arc/service/AuthServiceImplTest.java, src/test/java/it/gov/pagopa/arc/utils/SecurityUtilsTest.java
added controller and services for user info endpoint
added tests
required to show the information about authenticated user
=> feat: [P4PU-385] added controller and services and tests

src/main/java/it/gov/pagopa/arc/config/OAuth2LoginConfig.java, src/main/java/it/gov/pagopa/arc/security/JwtAuthenticationFilter.java, src/test/java/it/gov/pagopa/arc/config/OAuth2LoginConfigTest.java, src/test/java/it/gov/pagopa/arc/controller/AuthControllerImplTest.java, src/test/java/it/gov/pagopa/arc/controller/PaymentNoticesControllerImplTest.java, src/test/java/it/gov/pagopa/arc/controller/TransactionsControllerTest.java, src/test/java/it/gov/pagopa/arc/security/JwtAuthenticationFilterTest.java
In this PR jwt filter was added to analyse the authentication token and if it is stored in local to provide user with security context
This functionality will provide a protected enpoint that will respond with user information in json format
=> feat: [P4PU-385] user info - added jwt filter

postman/pagopa-arc-E2E.postman_collection.json
This PR include postman test that are required to demonstrate the user info functionality
=> chore: [P4PU-375] added test for user info

helm/values-prod.yaml, helm/values-uat.yaml, postman/template-env.secure-file.json.txt
=> fix: [P4PU-417] Update domain

src/main/java/it/gov/pagopa/arc/config/ZendeskAssistanceTokenConfig.java, src/main/java/it/gov/pagopa/arc/dto/mapper/zendeskassistancetoken/ZendeskAssistanceTokenResponseMapper.java, src/main/java/it/gov/pagopa/arc/service/ZendeskAssistanceTokenBuilder.java, src/main/java/it/gov/pagopa/arc/service/ZendeskAssistanceTokenServiceImpl.java, src/main/java/it/gov/pagopa/arc/utils/SecurityUtils.java, src/main/java/it/gov/pagopa/arc/utils/Utilities.java, src/test/java/it/gov/pagopa/arc/config/ZendeskAssistanceTokenConfigSample.java, src/test/java/it/gov/pagopa/arc/config/ZendeskAssistanceTokenConfigTest.java, src/test/java/it/gov/pagopa/arc/controller/AssistanceControllerImplTest.java, src/test/java/it/gov/pagopa/arc/dto/mapper/zendeskassistancetoken/ZendeskAssistanceTokenResponseMapperTest.java, src/test/java/it/gov/pagopa/arc/service/ZendeskAssistanceTokenBuilderTest.java, src/test/java/it/gov/pagopa/arc/service/ZendeskAssistanceTokenServiceImplTest.java, src/test/java/it/gov/pagopa/arc/utils/SecurityUtilsTest.java, src/test/java/it/gov/pagopa/arc/utils/UtilitiesTest.java
- Added business logic to generate zendesk assistance jwt token
- added junit tests
=> feat: [P4PU-363] generate zendesk assistance jwt token

helm/values-dev.yaml
=> fix: Update dev domain 

openapi/pagopa-arc-be.openapi.yaml, src/main/java/it/gov/pagopa/arc/config/OAuth2LoginConfig.java, src/main/java/it/gov/pagopa/arc/exception/ArcExceptionHandler.java, src/main/java/it/gov/pagopa/arc/exception/custom/ZendeskAssistanceInvalidUserEmailException.java, src/main/java/it/gov/pagopa/arc/service/ZendeskAssistanceTokenServiceImpl.java, src/main/java/it/gov/pagopa/arc/utils/SecurityUtils.java, src/main/java/it/gov/pagopa/arc/utils/Utilities.java, src/test/java/it/gov/pagopa/arc/exception/ArcExceptionHandlerTest.java, src/test/java/it/gov/pagopa/arc/utils/SecurityUtilsTest.java, src/test/java/it/gov/pagopa/arc/utils/UtilitiesTest.java
- add custom exception
- added security schema ti assistance endpoint
=> fix: [P4PU-364] added custom exception to assistance flow

helm/values-dev.yaml, helm/values-uat.yaml
This PR proposes to fix the oneidentity callback uri.
=> fix: [P4PU-441] oneidentity callback uri

helm/values-dev.yaml, helm/values-uat.yaml, openapi/pagopa-arc-be.openapi.yaml, src/main/java/it/gov/pagopa/arc/config/OAuth2LoginConfig.java, src/main/java/it/gov/pagopa/arc/config/ZendeskAssistanceTokenConfig.java, src/main/java/it/gov/pagopa/arc/dto/mapper/zendeskassistancetoken/ZendeskAssistanceTokenResponseMapper.java, src/main/java/it/gov/pagopa/arc/exception/ArcExceptionHandler.java, src/main/java/it/gov/pagopa/arc/exception/custom/ZendeskAssistanceInvalidUserEmailException.java, src/main/java/it/gov/pagopa/arc/service/ZendeskAssistanceTokenBuilder.java, src/main/java/it/gov/pagopa/arc/service/ZendeskAssistanceTokenServiceImpl.java, src/main/java/it/gov/pagopa/arc/utils/SecurityUtils.java, src/main/java/it/gov/pagopa/arc/utils/Utilities.java, src/test/java/it/gov/pagopa/arc/config/ZendeskAssistanceTokenConfigSample.java, src/test/java/it/gov/pagopa/arc/config/ZendeskAssistanceTokenConfigTest.java, src/test/java/it/gov/pagopa/arc/controller/AssistanceControllerImplTest.java, src/test/java/it/gov/pagopa/arc/dto/mapper/zendeskassistancetoken/ZendeskAssistanceTokenResponseMapperTest.java, src/test/java/it/gov/pagopa/arc/exception/ArcExceptionHandlerTest.java, src/test/java/it/gov/pagopa/arc/service/ZendeskAssistanceTokenBuilderTest.java, src/test/java/it/gov/pagopa/arc/service/ZendeskAssistanceTokenServiceImplTest.java, src/test/java/it/gov/pagopa/arc/utils/SecurityUtilsTest.java, src/test/java/it/gov/pagopa/arc/utils/UtilitiesTest.java
* generate zendesk assistance jwt token
* fix: Update dev domain
=> feat: [P4PU-363] Promote to UAT

src/main/resources/application.yml
=> update fiscal code

postman/pagopa-arc-E2E.postman_collection.json, src/main/resources/application.yml
- Added assistance endpoint test
- removed bizEvents generic error tests
- fixed payment-notices tests
=> chore: [P4PU-365] update postman collection with assistance endpoint tests

src/main/java/it/gov/pagopa/arc/utils/Utilities.java, src/test/java/it/gov/pagopa/arc/dto/mapper/BizEventsInfoTransaction2InfoTransactionDTOTest.java, src/test/java/it/gov/pagopa/arc/fakers/bizEvents/BizEventsCartItemDTOFaker.java, src/test/java/it/gov/pagopa/arc/fakers/bizEvents/BizEventsInfoTransactionDTOFaker.java, src/test/java/it/gov/pagopa/arc/fakers/bizEvents/BizEventsTransactionDTOFaker.java, src/test/java/it/gov/pagopa/arc/utils/UtilitiesTest.java
- Fixed amount format
- updated test
=> fix: [P4PU-326] fixed amount format

openapi/pagopa-arc-be.openapi.yaml
- added actionUrl to ZendeskAssistanceTokenResponse
=> chore: [P4PU-471] added actionUrl to ZendeskAssistanceTokenResponse

src/test/java/it/gov/pagopa/arc/security/IdpIntegrationTest.java, src/test/resources/stub/mappings/idpService/idp_Get_well_known_OK.json
Added integration test that verify integration between arc and idp
=> chore: [P4PU-446] added integration tests

openapi/pagopa-arc-be.openapi.yaml
Added logout endpoint into arc
=> chore: [P4PU-403] logout endpoint

src/main/java/it/gov/pagopa/arc/service/TokenStoreService.java, src/main/java/it/gov/pagopa/arc/service/TokenStoreServiceImpl.java, src/test/java/it/gov/pagopa/arc/service/TokenStoreServiceImplTest.java
Added token store service delete method
Added unit test
=> feat: [P4PU-402] added token store service delete method

src/main/java/it/gov/pagopa/arc/config/OAuth2LoginConfig.java, src/main/java/it/gov/pagopa/arc/security/CustomLogoutHandler.java, src/main/java/it/gov/pagopa/arc/security/CustomLogoutSuccessHandler.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/arc/config/OAuth2LoginConfigTest.java, src/test/java/it/gov/pagopa/arc/security/CustomLogoutHandlerTest.java, src/test/java/it/gov/pagopa/arc/security/CustomLogoutSuccessHandlerTest.java
added filter for logout action
added unit test
=> feat: [P4PU-404] added updated filter for logout

postman/pagopa-arc-E2E.postman_collection.json
Added logout endpoint test into postman collection
=> feat: [P4PU-400] added test for logout endpoint

openapi/pagopa-arc-be.openapi.yaml, postman/pagopa-arc-E2E.postman_collection.json, src/main/java/it/gov/pagopa/arc/config/OAuth2LoginConfig.java, src/main/java/it/gov/pagopa/arc/security/CustomLogoutHandler.java, src/main/java/it/gov/pagopa/arc/security/CustomLogoutSuccessHandler.java, src/main/java/it/gov/pagopa/arc/security/InMemoryOAuth2AuthorizationRequestRepository.java, src/main/java/it/gov/pagopa/arc/service/TokenStoreService.java, src/main/java/it/gov/pagopa/arc/service/TokenStoreServiceImpl.java, src/main/java/it/gov/pagopa/arc/utils/Utilities.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/arc/config/OAuth2LoginConfigTest.java, src/test/java/it/gov/pagopa/arc/dto/mapper/BizEventsInfoTransaction2InfoTransactionDTOTest.java, src/test/java/it/gov/pagopa/arc/fakers/bizEvents/BizEventsCartItemDTOFaker.java, src/test/java/it/gov/pagopa/arc/fakers/bizEvents/BizEventsInfoTransactionDTOFaker.java, src/test/java/it/gov/pagopa/arc/fakers/bizEvents/BizEventsTransactionDTOFaker.java, src/test/java/it/gov/pagopa/arc/security/CustomLogoutHandlerTest.java, src/test/java/it/gov/pagopa/arc/security/CustomLogoutSuccessHandlerTest.java, src/test/java/it/gov/pagopa/arc/security/IdpIntegrationTest.java, src/test/java/it/gov/pagopa/arc/security/InMemoryOAuth2AuthorizationRequestRepositoryTest.java, src/test/java/it/gov/pagopa/arc/service/TokenStoreServiceImplTest.java, src/test/java/it/gov/pagopa/arc/utils/UtilitiesTest.java, src/test/resources/stub/mappings/idpService/idp_Get_well_known_OK.json
=> feat: [P4PU-400] Promote to UAT

helm/values.yaml, src/main/java/it/gov/pagopa/arc/config/ZendeskAssistanceTokenConfig.java, src/main/java/it/gov/pagopa/arc/dto/mapper/zendeskassistancetoken/ZendeskAssistanceTokenResponseMapper.java, src/main/java/it/gov/pagopa/arc/service/ZendeskAssistanceTokenServiceImpl.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/arc/config/ZendeskAssistanceTokenConfigSample.java, src/test/java/it/gov/pagopa/arc/dto/mapper/zendeskassistancetoken/ZendeskAssistanceTokenResponseMapperTest.java, src/test/java/it/gov/pagopa/arc/service/ZendeskAssistanceTokenServiceImplTest.java
- update business logic assistance to also return the Zendesk action URL in response
- update tests
=> fix: [P4PU-472] update business logic assistance to also return the Zendesk action URL in response

postman/pagopa-arc-E2E.postman_collection.json, postman/template-env.secure-file.json.txt
-updated collection postman assistance test 
-updated template secure file
=> chore: [P4PU-473] updated collection postman assistance test and template secure file

src/main/java/it/gov/pagopa/arc/dto/IamUserInfoDTO.java, src/test/java/it/gov/pagopa/arc/dto/IamUserInfoDTOTest.java
Added logic to replace TINIT- prefix from fiscalCode field
=> feat: [P4PU-459] added parsing on fiscal code to remove prefix TINIT-

src/main/java/it/gov/pagopa/arc/config/OAuth2LoginConfig.java
Removed security on actuator endpoint for liveness probe
=> chore: [P4PU-437] added permit all on actuator endpoints

openapi/pagopa-arc-be.openapi.yaml
Updated open api by adding bearer auth token requirement
=> feat: [P4PU-376] added bearer auth token requirement for all endpoints

src/main/java/it/gov/pagopa/arc/service/bizevents/BizEventsServiceImpl.java, src/main/java/it/gov/pagopa/arc/service/pullpayment/PullPaymentServiceImpl.java, src/main/java/it/gov/pagopa/arc/utils/SecurityUtils.java, src/test/java/it/gov/pagopa/arc/service/bizevents/BizEventsServiceImplTest.java, src/test/java/it/gov/pagopa/arc/service/pullpayment/PullPaymentServiceImplTest.java, src/test/java/it/gov/pagopa/arc/utils/SecurityUtilsTest.java
- updated services with getUserFiscalCode method
- Updated tests
=> feat: [P4PU-390] update business logic to recovery cf from session

src/main/java/it/gov/pagopa/arc/dto/mapper/DateTimeTruncate.java, src/main/java/it/gov/pagopa/arc/dto/mapper/pullpayment/PullPaymentInstallmentDTO2InstallmentDTO.java, src/main/java/it/gov/pagopa/arc/dto/mapper/pullpayment/PullPaymentNoticeDTO2PaymentNoticeDTO.java, src/test/java/it/gov/pagopa/arc/dto/mapper/DateTimeTruncateTest.java, src/test/java/it/gov/pagopa/arc/dto/mapper/pullpayment/PullPaymentInstallmentDTO2InstallmentDTOTest.java, src/test/java/it/gov/pagopa/arc/fakers/paymentNotices/PaymentNoticeDTOFaker.java
- update datetime format of the payment-notices response 
- added test
=> fix: [P4PU-387] update datetime format of the payment-notices response 

openapi/pagopa-arc-be.openapi.yaml
Added endpoint for generating instance of autenticated user for testing purpose
=> chore: [P4PU-481] updated api endpoint

openapi/pagopa-arc-be.openapi.yaml, src/main/java/it/gov/pagopa/arc/config/OAuth2LoginConfig.java, src/main/java/it/gov/pagopa/arc/controller/AuthControllerImpl.java, src/main/java/it/gov/pagopa/arc/service/AuthService.java, src/main/java/it/gov/pagopa/arc/service/AuthServiceImpl.java, src/test/java/it/gov/pagopa/arc/controller/AuthControllerImplTest.java, src/test/java/it/gov/pagopa/arc/service/AuthServiceImplTest.java
Added endpoint for retriving test user 
Updated test 
Unprotected test user enpoint
=> chore: [P4PU-482] add business logic

CODEOWNERS, README.md
=> fix: Update codeowners

.devops/deploy-pipelines.yml
- Fixed Warning on deploy pipeline
=> fix: [P4PU-272] fix warning pipeline

postman/pagopa-arc-E2E.postman_collection.json
=> fix: [P4PU-522] fixed collection postman

src/main/resources/application.yml
=> fix: Update application.yml

helm/values.yaml, src/main/java/it/gov/pagopa/arc/connector/bizevents/BizEventsConnectorImpl.java, src/main/java/it/gov/pagopa/arc/connector/bizevents/BizEventsRestClient.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/arc/connector/bizevents/BizEventsConnectorImplTest.java, src/test/java/it/gov/pagopa/arc/security/IdpIntegrationTest.java
- added properties on application yaml
- updated values
- updated connector reference
=> chore: [P4PU-510] added paids properties

postman/pagopa-arc-E2E.postman_collection.json
=> chore: [P4PU-391] updated tests

openapi/pagopa-arc-be.openapi.yaml
- added notices endpoint in swagger
=> feat: [P4PU-505] added notices endpoint in swagger

postman/pagopa-arc-E2E.postman_collection.json, src/main/java/it/gov/pagopa/arc/security/CustomEntryPoint.java, src/main/java/it/gov/pagopa/arc/security/CustomLogoutHandler.java, src/main/java/it/gov/pagopa/arc/security/CustomLogoutSuccessHandler.java, src/test/java/it/gov/pagopa/arc/security/CustomEntryPointTest.java, src/test/java/it/gov/pagopa/arc/security/CustomLogoutSuccessHandlerTest.java
Update logout endpoint if not token is present bad request is returned
=> feat: [P4PU-474] update logout endpoint

.devops/deploy-pipelines.yml, helm/Chart.lock, helm/Chart.yaml, helm/values.yaml
=> chore: [P4PU-526] apply workload-identity

openapi/pagopa-arc-be.openapi.yaml
- added notice details endpoint
=> chore: [P4PU-531] added notice details endpoint

openapi/pagopa-arc-be.openapi.yaml, src/main/java/it/gov/pagopa/arc/connector/bizevents/dto/paidnotice/BizEventsInfoPaidNoticeDTO.java, src/main/java/it/gov/pagopa/arc/connector/bizevents/dto/paidnotice/BizEventsPaidNoticeDetailsDTO.java, src/main/java/it/gov/pagopa/arc/connector/bizevents/paidnotice/BizEventsPaidNoticeConnector.java, src/main/java/it/gov/pagopa/arc/connector/bizevents/paidnotice/BizEventsPaidNoticeConnectorImpl.java, src/main/java/it/gov/pagopa/arc/connector/bizevents/paidnotice/BizEventsPaidNoticeRestClient.java, src/main/java/it/gov/pagopa/arc/exception/ArcExceptionHandler.java, src/main/java/it/gov/pagopa/arc/exception/custom/BizEventsPaidNoticeNotFoundException.java, src/test/java/it/gov/pagopa/arc/connector/bizevents/paidnotice/BizEventsPaidNoticeConnectorImplTest.java, src/test/java/it/gov/pagopa/arc/exception/ArcExceptionHandlerTest.java, src/test/resources/stub/mappings/bizEventsService/bizEvents_Get_PaidNoticeDetails_ERROR.json, src/test/resources/stub/mappings/bizEventsService/bizEvents_Get_PaidNoticeDetails_NOT_FOUND.json, src/test/resources/stub/mappings/bizEventsService/bizEvents_Get_PaidNoticeDetails_OK.json
- added endpoint paid notice details on rest client bizEvents
=> chore: [P4PU-532] update feign client with endpoint details paid notice

src/main/java/it/gov/pagopa/arc/controller/NoticesControllerImpl.java, src/main/java/it/gov/pagopa/arc/service/NoticesService.java, src/main/java/it/gov/pagopa/arc/service/NoticesServiceImpl.java, src/main/java/it/gov/pagopa/arc/service/bizevents/BizEventsService.java, src/main/java/it/gov/pagopa/arc/service/bizevents/BizEventsServiceImpl.java, src/test/java/it/gov/pagopa/arc/controller/NoticesControllerImplTest.java, src/test/java/it/gov/pagopa/arc/service/NoticesServiceImplTest.java, src/test/java/it/gov/pagopa/arc/service/bizevents/BizEventsServiceImplTest.java
- added business logic to retrieve notice details
- added tests
=> feat: [P4PU-534] added business logic to retrieve notice details

src/main/java/it/gov/pagopa/arc/dto/mapper/bizevents/paidnotice/BizEventsInfoPaidNoticeDTO2InfoNoticeDTOMapper.java, src/main/java/it/gov/pagopa/arc/dto/mapper/bizevents/paidnotice/BizEventsPaidNoticeDetailsDTO2NoticeDetailsDTOMapper.java, src/test/java/it/gov/pagopa/arc/dto/mapper/bizevents/paidnotice/BizEventsInfoPaidNoticeDTO2InfoNoticeDTOMapperTest.java, src/test/java/it/gov/pagopa/arc/dto/mapper/bizevents/paidnotice/BizEventsPaidNoticeDetailsDTO2NoticeDetailsDTOMapperTest.java
=> fix: [P4PU-591] fixed mapper

openapi/pagopa-arc-be.openapi.yaml
=> chore: [P4PU-543] added receipt endpoint

src/main/java/it/gov/pagopa/arc/connector/bizevents/paidnotice/BizEventsPaidNoticeConnector.java, src/main/java/it/gov/pagopa/arc/connector/bizevents/paidnotice/BizEventsPaidNoticeConnectorImpl.java, src/main/java/it/gov/pagopa/arc/connector/bizevents/paidnotice/BizEventsPaidNoticeRestClient.java, src/test/java/it/gov/pagopa/arc/connector/bizevents/paidnotice/BizEventsPaidNoticeConnectorImplTest.java, src/test/resources/stub/mappings/bizEventsService/bizEvents_Get_PaidNoticeReceipt_ERROR.json, src/test/resources/stub/mappings/bizEventsService/bizEvents_Get_PaidNoticeReceipt_NOT_FOUND.json, src/test/resources/stub/mappings/bizEventsService/bizEvents_Get_PaidNoticeReceipt_OK.json
- Added  endpoint paids pdf in on feign client
- Added tests
=> chore: [P4PU-542] update feign client with endpoint paids pdf

src/main/java/it/gov/pagopa/arc/controller/NoticesControllerImpl.java, src/main/java/it/gov/pagopa/arc/service/NoticesService.java, src/main/java/it/gov/pagopa/arc/service/NoticesServiceImpl.java, src/main/java/it/gov/pagopa/arc/service/bizevents/BizEventsService.java, src/main/java/it/gov/pagopa/arc/service/bizevents/BizEventsServiceImpl.java, src/test/java/it/gov/pagopa/arc/controller/NoticesControllerImplTest.java, src/test/java/it/gov/pagopa/arc/service/NoticesServiceImplTest.java, src/test/java/it/gov/pagopa/arc/service/bizevents/BizEventsServiceImplTest.java
-  implemented business logic to retrieve receipt
- added tests
=> feat: [P4PU-545] implements business logic to retrieve receipt

postman/pagopa-arc-E2E.postman_collection.json
=> chore: [P4PU-546] updated test postman with receipt test

openapi/pagopa-arc-be.openapi.yaml, postman/pagopa-arc-E2E.postman_collection.json, src/main/java/it/gov/pagopa/arc/config/OAuth2LoginConfig.java, src/main/java/it/gov/pagopa/arc/connector/bizevents/paidnotice/BizEventsPaidNoticeConnector.java, src/main/java/it/gov/pagopa/arc/connector/bizevents/paidnotice/BizEventsPaidNoticeConnectorImpl.java, src/main/java/it/gov/pagopa/arc/connector/bizevents/paidnotice/BizEventsPaidNoticeRestClient.java, src/main/java/it/gov/pagopa/arc/controller/NoticesControllerImpl.java, src/main/java/it/gov/pagopa/arc/exception/ArcExceptionHandler.java, src/main/java/it/gov/pagopa/arc/security/CustomAuthenticationEntryPoint.java, src/main/java/it/gov/pagopa/arc/service/NoticesService.java, src/main/java/it/gov/pagopa/arc/service/NoticesServiceImpl.java, src/main/java/it/gov/pagopa/arc/service/bizevents/BizEventsService.java, src/main/java/it/gov/pagopa/arc/service/bizevents/BizEventsServiceImpl.java, src/test/java/it/gov/pagopa/arc/connector/bizevents/paidnotice/BizEventsPaidNoticeConnectorImplTest.java, src/test/java/it/gov/pagopa/arc/controller/NoticesControllerImplTest.java, src/test/java/it/gov/pagopa/arc/exception/ArcExceptionHandlerTest.java, src/test/java/it/gov/pagopa/arc/security/CustomAuthenticationEntryPointTest.java, src/test/java/it/gov/pagopa/arc/service/NoticesServiceImplTest.java, src/test/java/it/gov/pagopa/arc/service/bizevents/BizEventsServiceImplTest.java, src/test/resources/stub/mappings/bizEventsService/bizEvents_Get_PaidNoticeReceipt_ERROR.json, src/test/resources/stub/mappings/bizEventsService/bizEvents_Get_PaidNoticeReceipt_NOT_FOUND.json, src/test/resources/stub/mappings/bizEventsService/bizEvents_Get_PaidNoticeReceipt_OK.json
- Added receipt endpoint
- updated test postman
=> feat: [P4PU-000] Promote to UAT

openapi/pagopa-arc-be.openapi.yaml
=> chore: [P4PU-373] fixed warning openapi generate

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
- activated application insights in all environment
=> chore: [P4PU-636] activated application insights in all environment

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
- Activated application insights in all environment
=> chore: [P4PU-000] Promote to UAT

postman/pagopa-arc-E2E.postman_collection.json
removed api call to removed api from postman collection
=> feat: [P4PU-669] removed api call to removed api from postman collection

.github/workflows/code-review.yml, build.gradle.kts
- updated code-review with libraries
=> fix: [P4PU-327] updated code-review with libraries 

.github/workflows/code-review.yml
- updated exclusions on code-review
=> fix: [P4PU-678] updated exclusions on code-review

.github/workflows/code-review.yml
- updated sonar cloud  exclusions path
=> fix: [P4PU-682] updated sonar cloud  exclusions path

.github/workflows/code-review.yml
- fix exclusions pattern code-review
=> fix: [P4PU-000] fix exclusions pattern code-review

.github/workflows/payments-flow-docker-snapshot.yml, .github/workflows/payments-flow-release.yml
=> fix: payments updated actions with tag version 1.19.2

.github/workflows/trivy.yml
-  added send slack notification step
=> feat: [P4PU-668]  added send slack notification step

src/main/java/it/gov/pagopa/arc/dto/mapper/MapperUtilities.java, src/main/java/it/gov/pagopa/arc/dto/mapper/bizevents/paidnotice/BizEventsInfoPaidNoticeDTO2InfoNoticeDTOMapper.java, src/test/java/it/gov/pagopa/arc/dto/mapper/MapperUtilitiesTest.java, src/test/java/it/gov/pagopa/arc/dto/mapper/bizevents/paidnotice/BizEventsInfoPaidNoticeDTO2InfoNoticeDTOMapperTest.java, src/test/java/it/gov/pagopa/arc/fakers/InfoNoticeDTOFaker.java
- updated mapper
- updated tests
=> fix: [P4PU-739] update mapper

openapi/pagopa-arc-be.openapi.yaml
- updated swagger with payment notice details API
=> chore: [P4PU-750] updated swagger with payment notice details API

src/main/java/it/gov/pagopa/arc/config/FeignConfig.java, src/main/java/it/gov/pagopa/arc/connector/gpd/GPDConnector.java, src/main/java/it/gov/pagopa/arc/connector/gpd/GPDConnectorImpl.java, src/main/java/it/gov/pagopa/arc/connector/gpd/GPDRestClient.java, src/main/java/it/gov/pagopa/arc/connector/gpd/dto/GPDPaymentNoticeDetailsDTO.java, src/main/java/it/gov/pagopa/arc/connector/gpd/dto/GPDPaymentOptionDetailsDTO.java, src/main/java/it/gov/pagopa/arc/connector/gpd/dto/GPDPaymentOptionMetadataDTO.java, src/main/java/it/gov/pagopa/arc/connector/gpd/dto/GPDTransferDTO.java, src/main/java/it/gov/pagopa/arc/connector/gpd/dto/GPDTransferStampDTO.java, src/main/java/it/gov/pagopa/arc/connector/gpd/enums/GPDDebtorType.java, src/main/java/it/gov/pagopa/arc/connector/gpd/enums/GPDPaymentNoticeDetailsStatus.java, src/main/java/it/gov/pagopa/arc/connector/gpd/enums/GPDPaymentOptionDetailsStatus.java, src/main/java/it/gov/pagopa/arc/connector/gpd/enums/GPDTransferStatus.java, src/main/java/it/gov/pagopa/arc/connector/pullpayment/PullPaymentRestClient.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/arc/connector/gpd/GPDConnectorImplTest.java, src/test/java/it/gov/pagopa/arc/fakers/connector/gpd/GPDPaymentNoticeDetailsDTOFaker.java, src/test/java/it/gov/pagopa/arc/fakers/connector/gpd/GPDPaymentOptionDetailsDTOFaker.java, src/test/java/it/gov/pagopa/arc/fakers/connector/gpd/GPDPaymentOptionMetadataDTOFaker.java, src/test/java/it/gov/pagopa/arc/fakers/connector/gpd/GPDTransferDTOFaker.java, src/test/java/it/gov/pagopa/arc/fakers/connector/gpd/GPDTransferStampDTOFaker.java, src/test/java/it/gov/pagopa/arc/security/IdpIntegrationTest.java, src/test/resources/stub/mappings/gpd/gpd_Get_PaymentNoticeDetails_BAD_REQUEST.json, src/test/resources/stub/mappings/gpd/gpd_Get_PaymentNoticeDetails_ERROR.json, src/test/resources/stub/mappings/gpd/gpd_Get_PaymentNoticeDetails_INSTALLMENTS_OK.json, src/test/resources/stub/mappings/gpd/gpd_Get_PaymentNoticeDetails_NOT_FOUND.json, src/test/resources/stub/mappings/gpd/gpd_Get_PaymentNoticeDetails_OK.json
- Added GPD Feign client
- Added stubs
- Added tests
=> chore: [P4PU-751] create GPD feign client

src/main/java/it/gov/pagopa/arc/connector/gpd/GPDConnectorImpl.java, src/main/java/it/gov/pagopa/arc/exception/ArcExceptionHandler.java, src/main/java/it/gov/pagopa/arc/exception/custom/GPDInvalidRequestException.java, src/main/java/it/gov/pagopa/arc/exception/custom/GPDInvocationException.java, src/main/java/it/gov/pagopa/arc/exception/custom/GPDPaymentNoticeDetailsNotFoundException.java, src/test/java/it/gov/pagopa/arc/connector/gpd/GPDConnectorImplTest.java, src/test/java/it/gov/pagopa/arc/exception/ArcExceptionHandlerTest.java
=> fix: [P4PU-753] added custom exception

src/main/java/it/gov/pagopa/arc/controller/PaymentNoticesControllerImpl.java, src/main/java/it/gov/pagopa/arc/service/PaymentNoticesService.java, src/main/java/it/gov/pagopa/arc/service/PaymentNoticesServiceImpl.java, src/main/java/it/gov/pagopa/arc/service/gpd/GPDService.java, src/main/java/it/gov/pagopa/arc/service/gpd/GPDServiceImpl.java, src/test/java/it/gov/pagopa/arc/controller/PaymentNoticesControllerImplTest.java, src/test/java/it/gov/pagopa/arc/service/PaymentNoticesServiceImplTest.java, src/test/java/it/gov/pagopa/arc/service/gpd/GPDServiceImplTest.java
=> feat: [P4PU-755] added business logic

postman/pagopa-arc-E2E.postman_collection.json
- added test postman API paymentNoticesDetails
=> chore: [P4PU-756] added test postman API paymentNoticesDetails

openapi/pagopa-arc-be.openapi.yaml, src/main/java/it/gov/pagopa/arc/dto/mapper/pullpayment/PullPaymentInstallmentDTO2InstallmentDTOMapper.java, src/main/java/it/gov/pagopa/arc/dto/mapper/pullpayment/PullPaymentNoticeDTO2PaymentNoticeDTOMapper.java, src/test/java/it/gov/pagopa/arc/dto/mapper/pullpayment/PullPaymentInstallmentDTO2InstallmentDTOMapperTest.java, src/test/java/it/gov/pagopa/arc/dto/mapper/pullpayment/PullPaymentNoticeDTO2PaymentNoticeDTOMapperTest.java, src/test/java/it/gov/pagopa/arc/dto/mapper/pullpayment/PullPaymentOptionDTO2PaymentOptionDTOMapperTest.java, src/test/java/it/gov/pagopa/arc/fakers/paymentNotices/InstallmentDTOFaker.java, src/test/java/it/gov/pagopa/arc/fakers/paymentNotices/PaymentNoticeDTOFaker.java, src/test/java/it/gov/pagopa/arc/fakers/paymentNotices/PaymentOptionDTOFaker.java
-  updated response of payment-notice API
=> fix: [P4PU-799] updated response of payment-notice API

openapi/pagopa-arc-be.openapi.yaml, src/main/java/it/gov/pagopa/arc/dto/mapper/pullpayment/PullPaymentInstallmentDTO2InstallmentDTOMapper.java, src/main/java/it/gov/pagopa/arc/dto/mapper/pullpayment/PullPaymentNoticeDTO2PaymentNoticeDTOMapper.java, src/test/java/it/gov/pagopa/arc/dto/mapper/pullpayment/PullPaymentInstallmentDTO2InstallmentDTOMapperTest.java, src/test/java/it/gov/pagopa/arc/dto/mapper/pullpayment/PullPaymentNoticeDTO2PaymentNoticeDTOMapperTest.java, src/test/java/it/gov/pagopa/arc/dto/mapper/pullpayment/PullPaymentOptionDTO2PaymentOptionDTOMapperTest.java, src/test/java/it/gov/pagopa/arc/fakers/paymentNotices/InstallmentDTOFaker.java, src/test/java/it/gov/pagopa/arc/fakers/paymentNotices/PaymentNoticeDTOFaker.java, src/test/java/it/gov/pagopa/arc/fakers/paymentNotices/PaymentOptionDTOFaker.java
-  updated swagger with new response of payment-notice API
=> fix: [P4PU-799] Promote to UAT

src/main/resources/application.yml
=> feat: [P4PU-761] added health endpoint

src/main/resources/application.yml
=> fix: [PAPU-000] removed details on health endpoint

postman/pagopa-arc-E2E.postman_collection.json
- added test postman for health endpoint
=> chore: [P4PU-818] added test postman for health endpoint

openapi/pagopa-arc-be.openapi.yaml, src/main/java/it/gov/pagopa/arc/controller/NoticesControllerImpl.java, src/test/java/it/gov/pagopa/arc/controller/NoticesControllerImplTest.java
- added header to receipt response
- updated tests
=> feat: [P4PU-825] added header to receipt response

postman/pagopa-arc-E2E.postman_collection.json
=> chore: [P4PU-827] updated collection postman

openapi/pagopa-arc-be.openapi.yaml
- updated swagger with post payment-notices endpoint
=> chore: [P4PU-837] updated swagger with post payment-notices endpoint

src/main/java/it/gov/pagopa/arc/connector/gpd/GPDConnector.java, src/main/java/it/gov/pagopa/arc/connector/gpd/GPDConnectorImpl.java, src/main/java/it/gov/pagopa/arc/connector/gpd/GPDRestClient.java, src/main/java/it/gov/pagopa/arc/connector/gpd/dto/GPDPaymentNoticeDetailsDTO.java, src/main/java/it/gov/pagopa/arc/connector/gpd/dto/GPDPaymentNoticePayloadDTO.java, src/main/java/it/gov/pagopa/arc/connector/gpd/dto/GPDPaymentOptionPayloadDTO.java, src/main/java/it/gov/pagopa/arc/connector/gpd/dto/GPDTransferPayloadDTO.java, src/main/java/it/gov/pagopa/arc/connector/gpd/enums/GPDPaymentNoticeStatus.java, src/test/java/it/gov/pagopa/arc/connector/gpd/GPDConnectorImplTest.java, src/test/java/it/gov/pagopa/arc/fakers/connector/gpd/GPDPaymentNoticeDetailsDTOFaker.java, src/test/java/it/gov/pagopa/arc/fakers/connector/gpd/GPDPaymentNoticePayloadDTOFaker.java, src/test/java/it/gov/pagopa/arc/fakers/connector/gpd/GPDPaymentOptionPayloadFaker.java, src/test/java/it/gov/pagopa/arc/fakers/connector/gpd/GPDTransferPayloadFaker.java, src/test/resources/stub/mappings/gpd/gpd_Post_GeneratePaymentNotice_BAD_REQUEST.json, src/test/resources/stub/mappings/gpd/gpd_Post_GeneratePaymentNotice_ERROR.json, src/test/resources/stub/mappings/gpd/gpd_Post_GeneratePaymentNotice_OK.json
- added DTOS
- updated GPD connector 
- added tests
=> feat: [P4PU-838] updated GPD connector with generate PD endpoint

postman/pagopa-arc-E2E.postman_collection.json
=> chore: [P4PU-841] updated collection postman

openapi/pagopa-arc-be.openapi.yaml
- update swagger with too many request
=> fix: [P4PU-875] update swagger with too many request

openapi/pagopa-arc-be.openapi.yaml
- update swagger with endpoint /organizations
=> chore: [P4PU-858] update swagger with endpoint /organizations

postman/pagopa-arc-E2E.postman_collection.json
=> chore: [P4PU-860] updated collection postman

.github/terraform/00_data.tf, .github/terraform/99_locals.tf
=> chore: [P4PU-706] add slack webhook
